In [1]:
import numpy as np 

In [2]:

marks = np.array([55, 72, 68, 90, 45, 88, 76, 60, 95, 50])

print("Sum:", np.sum(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))
print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Standard Deviation:", np.std(marks))
print("Variance:", np.var(marks))

Sum: 699
Minimum: 45
Maximum: 95
Mean: 69.9
Median: 70.0
Standard Deviation: 16.561702811003464
Variance: 274.29


In [3]:
data1 = np.array([48, 50, 51, 49, 52])
data2 = np.array([10, 90, 5, 95, 50])

print("Data1 Std:", np.std(data1))
print("Data2 Std:", np.std(data2))

Data1 Std: 1.4142135623730951
Data2 Std: 38.07886552931954


In [4]:

marks = np.array([55, 72, 68, 90, 45, 88, 76, 60, 95, 50])

print("Index of Min:", np.argmin(marks))
print("Index of Max:", np.argmax(marks))

Index of Min: 4
Index of Max: 8


In [6]:
arr = np.array([30, 10, 50, 20, 40])

print("Sorted:", np.sort(arr))
print("Original:", arr)
print(np.sort(arr)[::-1]) # [start:stop:-1]

Sorted: [10 20 30 40 50]
Original: [30 10 50 20 40]
[50 40 30 20 10]


In [9]:
scores = np.array([[85, 90, 78],
                   [92, 88, 95],
                   [70, 75, 80]])

print("Columns Sum:", np.sum(scores, axis=0))
print("Rows Sum:", np.sum(scores, axis=1))

print("Columns Mean:", np.mean(scores, axis=0))
print("Rows Mean:", np.mean(scores, axis=1))

Columns Sum: [247 253 253]
Rows Sum: [253 275 225]
Columns Mean: [82.33333333 84.33333333 84.33333333]
Rows Mean: [84.33333333 91.66666667 75.        ]


In [11]:
arr = np.array([1, 2, 3, 4, 5])
print(np.cumsum(arr))
print(np.cumprod(arr))

[ 1  3  6 10 15]
[  1   2   6  24 120]


In [14]:
arr = np.array([1.234, 2.567, 3.891, 4.123])

print(np.round(arr, 2))
print(np.floor(arr))
print(np.ceil(arr))

[1.23 2.57 3.89 4.12]
[1. 2. 3. 4.]
[2. 3. 4. 5.]


In [17]:
marks = np.array([55, 72, 68, 90, 45, 88, 76, 60, 95, 50])

print("25th percentile:", np.percentile(marks, 25))
print("50th percentile:", np.percentile(marks, 50))
print("75th percentile:", np.percentile(marks, 75))

25th percentile: 56.25
50th percentile: 70.0
75th percentile: 85.0


In [18]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

print("Correlation:\n", np.corrcoef(x, y))
print("Covariance:\n", np.cov(x, y))

Correlation:
 [[1. 1.]
 [1. 1.]]
Covariance:
 [[ 2.5  5. ]
 [ 5.  10. ]]
