In [1]:
import numpy as np

In [4]:
random_int = np.random.randint(1, 100)
print(random_int)

15


In [ ]:
random_int = np.random.randint(1, 100, size=10)
print(random_int)

[4 4 4 3 1 2 1 2 4 1]


In [7]:
random_int = np.random.randint(1, 100, size=(3, 4))
print(random_int)

[[ 5 86 46 69]
 [25 35 56 99]
 [40 85 64 86]]


In [8]:
arr = np.random.rand(5)
print(arr)

[0.63423624 0.46269336 0.78229357 0.61721344 0.28104591]


In [9]:
arr = np.random.rand(3, 3)
print(arr)

[[0.86273522 0.85358764 0.61417807]
 [0.55921612 0.47924545 0.91449294]
 [0.61508732 0.95625962 0.99810704]]


In [12]:
arr = np.random.uniform(10, 50, size=3)
print(arr)

[35.43357731 45.29020638 30.38082444]


In [16]:
arr = np.random.randn(5)
print(arr)

[-0.03366422 -1.01580768 -0.16022019  0.76865503 -1.68664339]


In [17]:
print(np.mean(arr))
print(np.std(arr))

-0.4255360904305786
0.8472143409004519


In [18]:
arr = np.random.normal(loc=70, scale=10, size=1000)
print("Mean:", np.mean(arr))
print("Std:", np.std(arr))

Mean: 70.07497509947028
Std: 9.999242293626507


In [21]:
np.random.seed(18)
arr = np.random.randint(1, 100, size=5)
print(arr)

np.random.seed(18)
arr = np.random.randint(1, 100, size=5)
print(arr)

[43 20 70 63 50]
[43 20 70 63 50]


In [22]:
np.random.seed(18)
arr = np.random.randint(1, 100, size=5)
print(arr)

[43 20 70 63 50]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

np.random.shuffle(arr)
print(arr)

[ 7  6  4  5  2  9  8  1 10  3]


In [30]:
arr = np.array([10, 20, 30, 40, 50])

# single = np.random.choice(arr)
# print("Single random choice:", single)

multiple = np.random.choice(arr, size=3, replace=False)
print("Multiple without repeat:", multiple)

Multiple without repeat: [40 30 10]
