In [1]:
import numpy as np 

In [2]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[2])
print(arr[4])

10
30
50


In [3]:
print(arr[-1])
print(arr[-3])

50
30


In [5]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(arr[0, 0])
print(arr[1, 1])
print(arr[2, 1])

1
5
8


In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])

print(arr[1:5])
print(arr[0:6:2])
print(arr[:3])
print(arr[4:])
print(arr[::-1])

[20 30 40 50]
[10 30 50]
[10 20 30]
[50 60 70]
[70 60 50 40 30 20 10]


In [14]:
arr = np.array([[1,  2,  3,  4],
                [5,  6,  7,  8],
                [9,  10, 11, 12],
                [13, 14, 15, 16]])

print(arr[0:2, 0:2])
print(arr[1:3, 2:4])
print(arr[:, 1])
print(arr[2, :])

[[1 2]
 [5 6]]
[[ 7  8]
 [11 12]]
[ 2  6 10 14]
[ 9 10 11 12]


In [15]:
print(arr[3])

[13 14 15 16]


In [16]:
print(arr[:, 1])

[ 2  6 10 14]


In [19]:
arr = np.array([10, 20, 30, 40, 50])
arr[2] = 99
arr[4] = 550
print(arr)

[ 10  20  99  40 550]


In [22]:
arr = np.array([[1,  2,  3,  4],
                [5,  6,  7,  8],
                [9,  10, 11, 12],
                [13, 14, 15, 16]])

arr[0,1] = 20
print(arr)

[[ 1 20  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [23]:
arr = np.array([10, 20, 30, 40, 50, 60])

indices = [1, 2, 4]
print(arr[indices])

[20 30 50]
