In [1]:
import numpy as np

In [2]:
# Python list way
numbers = [1, 2, 3, 4, 5]
result = []
for n in numbers:
    result.append(n + 10)
print(result)

[11, 12, 13, 14, 15]


In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
reuslt = arr1 + 10

print(reuslt)

[11 12 13 14 15]


In [4]:
arr1 = np.array([1, 2, 3, 4, 5])
reuslt = arr1 - 10

print(reuslt)

[-9 -8 -7 -6 -5]


In [5]:
arr1 = np.array([1, 2, 3, 4, 5])
reuslt = arr1 * 10

print(reuslt)

[10 20 30 40 50]


In [6]:
arr1 = np.array([1, 2, 3, 4, 5])
reuslt = arr1 / 10

print(reuslt)

[0.1 0.2 0.3 0.4 0.5]


In [7]:
import numpy as np

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [8]:
arr = np.array([4, 9, 16, 25])
print(np.sqrt(arr))

[2. 3. 4. 5.]


In [9]:
arr = np.array([-4, 9, -16, 25])
print(np.abs(arr))

[ 4  9 16 25]


In [10]:
arr = np.array([1.3, 2.5, 3.1, 0.2])
print(np.floor(arr))
print(np.ceil(arr))

[1. 2. 3. 0.]
[2. 3. 4. 1.]


In [11]:
arr = np.array([4, 9, 16, 25])
print(np.log10(arr))

[0.60205999 0.95424251 1.20411998 1.39794001]


In [12]:
arr = np.array([10, 20, 30, 40, 50])

print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

150
10
50
30.0
30.0
14.142135623730951


In [13]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))


[12 15 18]
[ 6 15 24]


In [14]:
arr = np.array([10, 20, 30, 40, 50])

print(arr > 25)
print(arr == 30)

[False False  True  True  True]
[False False  True False False]
