In [1]:
import numpy as np

In [3]:
arr_1d = np.array([10, 20, 30, 40, 50])

print(arr_1d)
print("Dimensions:", arr_1d.ndim)
print("Shape:", arr_1d.shape)

[10 20 30 40 50]
Dimensions: 1
Shape: (5,)


In [6]:
arr_2d = np.array([[1, 2, 3, 7],
                   [4, 5, 6, 8],
                   [7, 8, 9, 5]])

print(arr_2d)
print("Dimensions:", arr_2d.ndim)
print("Shape:", arr_2d.shape)

[[1 2 3 7]
 [4 5 6 8]
 [7 8 9 5]]
Dimensions: 2
Shape: (3, 4)


In [9]:
arr_3d = np.array([[[1, 2],
                   [3, 4]],
                   [[5, 6],
                   [7, 8]]])

print(arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
arr1 = np.zeros((3, 4))
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
arr2 = np.ones((4, 3))
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
arr3 = np.full((2, 3), 5)
arr3

array([[5, 5, 5],
       [5, 5, 5]])

In [16]:
arr4 = np.eye(5)
arr4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
arr5 = np.arange(0, 51, 5)
arr5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [22]:
arr = np.linspace(0, 10, 9)
print(arr)

[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]


In [25]:
arr = np.random.randint(1, 50, size=(4, 3))
print(arr)

[[46 10 17]
 [13 40  4]
 [ 6 36  1]
 [ 6 35 13]]


In [30]:
arr = np.random.rand(4, 3)
print(arr)

[[0.09474046 0.78390529 0.15195519]
 [0.3393265  0.15317115 0.66721784]
 [0.96064718 0.97527547 0.98304247]
 [0.83623021 0.669051   0.22972168]]
