In [1]:
import numpy as np 

In [ ]:
# arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) # (no of 2d, no of rows, no of columns)

# print(arr1.shape)
# print(arr2.shape)
# print(arr3.shape)


(2, 2, 3)


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6])

reshaped = arr.reshape(2, 3)
print(reshaped)
print("Shape:", reshaped.shape)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [13]:
arr = np.arange(1, 13)
print("Original:", arr)

shape1 = arr.reshape(3, 4)
print("3x4:\n", shape1)

shape2 = arr.reshape(4, 3)
print("4x3:\n", shape2)

shape3 = arr.reshape(2, 2, 3)
print("2x2x3:\n", shape3)

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]
3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
4x3:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2x2x3:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [16]:
arr = np.arange(1, 16)

reshaped = arr.reshape(3, -1)
print(reshaped)
print("Shape:", reshaped.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Shape: (3, 5)


In [17]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

flat = arr.flatten()
print(flat)
print("Shape:", flat.shape)

[1 2 3 4 5 6 7 8 9]
Shape: (9,)


In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

flat = arr.flatten()
ravel = arr.ravel()

print(flat)
print(ravel)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [21]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr)
print("Original shape:", arr.shape)
transposed = arr.T
print("Transposed shape:", transposed.shape)
print(transposed)

[[1 2 3]
 [4 5 6]]
Original shape: (2, 3)
Transposed shape: (3, 2)
[[1 4]
 [2 5]
 [3 6]]


In [26]:
arr = np.array([1, 2, 3, 4, 5])
print("Original shape:", arr.shape)

arr_reshape = arr.reshape(5,1)
print(arr_reshape)

arr_row = arr[np.newaxis, :]
print("Row vector shape:", arr_row.shape)
print(arr_row)

arr_col = arr[:, np.newaxis]
print("Column vector shape:", arr_col.shape)
print(arr_col)

Original shape: (5,)
[[1]
 [2]
 [3]
 [4]
 [5]]
Row vector shape: (1, 5)
[[1 2 3 4 5]]
Column vector shape: (5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]
